
version: '3'

services:

  manage:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - prerender
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"

  urlToHtml:
    image: scbd/url-to-html-api:prerender-dev
    ports:
      - 7100:7100
    restart: always
    networks:
      - prerender
    stop_grace_period: 35s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 2500M
        reservations:
          cpus: '1'
          memory: 1250M

  stats:
    image: scbd/url-to-html-api:prerender-dev
    command: ["node", "src/stats/server.js"]
    restart: always
    environment:
      - SLACK_BOT_TOKEN
      - SLACK_CHANNEL_ID
      - SLACK_TEST_MODE
    ports:
      - target: 7200
        published: 7200
        protocol: tcp
        mode: host
    networks:
      - prerender
    volumes:
      - stats-data:/usr/src/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M

networks:
  prerender:
    external: true
  proxy:
    external: true

volumes:
  portainer-data:
  nginx-data:
  stats-data:
        